diff_drive_controller_effort:
  type        : "diff_drive_controller_effort/DiffDriveControllerEffort"
  left_wheel  : 'left_wheel_joint'
  right_wheel : 'right_wheel_joint'

  publish_rate: 20.0
  cmd_torque_timeout: 1.0
  wheel_separation : 0.18
  wheel_radius : 0.065
  pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  publish_wheel_joint_controller_state: True

  # tf
  #enable_odom_tf: true
  base_frame_id: base_link
  odom_frame_id: odom

  # limits
  has_torque_limits    : true
  max_torque           :  1.2 # Nm
    
  #has_acceleration_limits: true
  #max_acceleration       :  1.5 # m/s^2
  #min_acceleration       : -1.5 # m/s^2